#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Ensure we have updated standard packages
echo "* Updating standard packages.";
pkg_delete -v nodejs smtools
pkg_add -v nodejs smtools dtracetools htop
npm install smartdc -g
npm install jsontool -g

# Configuring image specific packages
echo "* Configuring image specific packages.";
curl -k https://snappy-java.googlecode.com/files/snappy-java-1.0.5.jar -o /opt/local/share/cassandra/lib/snappy-java-1.0.5.jar
# Setup PATH for Cassandra
cat >> /etc/profile <<EOF
export "PATH=$PATH:/opt/local/share/cassandra/bin";
EOF

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
